### ISSUE TITLE
Question about train_mb.py and tester_cam.py

### ISSUE THREAD

**Issue by ruler9527** [plusmultiply/mprm#1]
Thanks for sharing your code! But I have a question. When training and testing the code(train_mb.py and tester_cam.py）, I found that dataset.input_labels[] was not found. It turns out that self.input_labels is commented out in Scannet_subcloud.py, there only exists self.subcloud_labels. After replacing dataset.input_labels in these two files with dataset.subcloud_labels, the following error will appear(Appear in the validation phase). What should I do?

 File "/home/chn/Downloads/mprm-master/datasets/Scannet_subcloud.py", line 718, in spatially_regular_gen
    cloud_labels = self.subcloud_labels[data_split][cloud_ind][point_ind][1:]
IndexError: index 2173 is out of bounds for axis 0 with size 30

I think the code in trainer_mb.py and tester_cam.py does not correspond to the code in Scannet_subcloud.py. Please fix this bug.

**Comment by plusmultiply** [comment]
Thanks for pointing out the problem.
I updated the dataloader to load subcloud labels from npy files.  I forget to update the testing codes. I will fix this problem.

**Comment by ruler9527** [comment]
> 
> 
> Thanks for pointing out the problem.
> I updated the dataloader to load subcloud labels from npy files. I forget to update the testing codes. I will fix this problem.

OK, thanks ~ Looking forward to your updated code.

**Comment by plusmultiply** [comment]
I replaced the Scannet_subcloud.py with the previous version that generate subcloud label online. You can use this version first and I will fix the problem later.
