### ISSUE TITLE
About training_segmentation.py and Scannet_on_pseudo_label.py

### ISSUE THREAD

**Issue by ruler9527** [plusmultiply/mprm#2]
Through training I have been able to obtain the model and produce the result files of the .ply through generate_pseudo_label.py (the .ply files can be refined through crf_postprocess.py). But when I tried to use training_segmentation.py to use pseudo labels for segmentation model training, I found some errors in the code. First, there is no KPFCNN_model_original.py file under the Models folder, Then pseudo labels are read into the network in Scannet_on_pseudo_lable.py of the .npy format, but without producing (only the .ply files).
Because of these two problems, a new segmentation model cannot be retrained. I hope you can fix it. Thank you very much~

**Comment by plusmultiply** [comment]
Sorry for the trouble, I will fix the problems.

**Comment by plusmultiply** [comment]
I have commited the KPFCNN_model_original.py file. I accidentally commented the lines that save npy file  in crf_postprocess.py. And I have modified that, so you can generate the pseudo label in npy file using crf_postprocess.py.
